export default CategoryType = {
    MANUFACTURE: 1,
    CAR_MODEL: 2,
    PRODUCT_CATEGORY: 3,
    PRODUCT_COLOR: 4,
    PRODUCT_TRADEMARK: 5,
    PRODUCT_ORIGIN: 6,
    PRODUCT_SIZE: 7,
    STAFF_TYPE: 8,
    PARTNER_FIELD: 9,
    PARTNER: 10,
    VEHICLE_PARTS: 11,
    APPOINTMENT_SERVICE: 12,
    APPOINTMENT_SERVICE_TIME: 13
}