export default UserRole = {
    ADMINISTRATOR: "ADMINISTRATOR",
    TEACHER: "TEACHER",
    USER: "USER",
    EDITOR: "EDITOR",
    SALE: "SALE",
    TEACHER_SPEAKING: "TEACHER_SPEAKING",
    MARK_WRITING: "MARK_WRITING",
    SCHOOL: "SCHOOL",
    TESTER:"TESTER",
    CUSTOMER: "CUSTOMER"
}